development:
  username: root
  adapter:  'mysql2'
  database: mediapoints
  pool: 20
  timeout: 5000
  encoding: utf8

test:
  adapter: 'mysql2' 
  database: mediapoints_test
  username: root
  pool: 20
  timeout: 5000
  encoding: utf8

production:
  adapter: 'mysql2'
  database: mediapoints_prod
  username: root
  password: root
  pool: 20
  timeout: 5000
  encoding: utf8
